### ISSUE TITLE
Mais informações no README

### ISSUE THREAD

**Issue by henriquecrang** [gedrickbartz/Loja-de-Notebooks#1]
Recebi o link para o projeto no grupo de uma comunidade de desenvolvedores, mas sem informações no README sobre o que esse projeto se propõe a fazer e quais tecnologias usar, fiquei sem saber como eu poderia ajudar.

**Comment by gedrickbartz** [comment]
Bom dia Sr. Genrique de Andrade. Realmente o README estava muito pobre 
de informacoes. Porem ja foi atualizado e conforme o projeto for 
evoluindo sera melhorada. Grato

---

Em 28/07/2021 07:35, Henrique de Andrade escreveu:

> Recebi o link para o projeto no grupo de uma comunidade de 
> desenvolvedores, mas sem informações no README sobre o que esse projeto 
> se propõe a fazer e quais tecnologias usar, fiquei sem saber como eu 
> poderia ajudar.
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/gedrickbartz/Loja-de-Notebooks/issues/1
[2]

**Comment by henriquecrang** [comment]
Quando entender que já está suficiente para uma primeira versão você pode marcar essa issue como fechada.
